### ISSUE TITLE
Ajouter des ancres partout

### ISSUE THREAD

**Issue by antoinebigard** [mission-apprentissage/cerfa#276]
**Besoin:**
- [ ] pouvoir naviguer simplement avec les blocs formulaire
- [ ] pour les liens des messages d'alertes de données manquantes
- [ ] pour le support lorsque un utilisateur partage un lien

**Todo:**
- [ ] Input ids everywhere
- [x] Test d'ouverture de l’accordéon
